<?php

namespace VendaBundle\Repository;

/**
 * ItemPedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemPedidoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByIdPedido($idPedido)
    {
        $qb = $this->createQueryBuilder('i');
        $qb->select('i.id, i.pedidoId, i.produtoId, i.quantidade, i.precoUnitario, i.percentualDesconto, i.total, p.nome, p.codigo')
            ->innerJoin('VendaBundle:Produto', 'p', 'WITH', 'i.produtoId = p.id')
            ->where('i.pedidoId = :idPedido')
            ->setParameter('idPedido', $idPedido);
        return $qb->getQuery()->getResult();
    }

    public function getTotalPedido($idPedido)
    {
        $qb = $this->createQueryBuilder('i');
        $qb->select('sum (i.total) as total')
            ->where('i.pedidoId = :idPedido')
            ->setParameter('idPedido', $idPedido);
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function deleteItemPedido($idItemPedido)
    {
        $qb = $this->createQueryBuilder('i');
        $qb->delete('VendaBundle:ItemPedido', 'i')
            ->where('i.id = :idItemPedido')
            ->setParameter('idItemPedido', $idItemPedido);

        return $qb->getQuery()->getResult();
    }
}
