<?php

namespace VendaBundle\Tests\Controller;


class PedidoControllerTestTest extends \PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

}
